### ISSUE TITLE
.getBoundingClientRect() is inconsistent when spammed

### ISSUE THREAD

**Issue by joker314** [joker314/De-Redacted#1]
Observe that when you spam `.getBoundingClientRect()`, sometimes the value is inaccurate (perhaps some sort of caching occurs)?

@towerofnix, sorry to CC you in, but I was wondering if this was the same in Firefox and my device simply doesn't have the memory to have comfortably have two browsers at the same time while doing things?

**Comment by towerofnix** [comment]
@joker314 It would help if you had 1) a minimal repro case or 2) at least a working HTML file where I can test exactly the same code as you :)

**Comment by joker314** [comment]
@towerofnix index.js should just run

EDIT: Just realised index.js is an HTML file. Doesn't matter too much for now though

**Comment by towerofnix** [comment]
OKAY FINE I'll clone and rename it but REALLY you should rename it in the repo so I can run it on github pages!!! :P

**Comment by towerofnix** [comment]
Ann persistently measures (32, 32) for me.

**Comment by joker314** [comment]
How do you get it to run on GH pages? Do I have to stick it in a special branch?

EDIT: Okay, renamed file

**Comment by joker314** [comment]
@towerofnix You get integers?

EDIT: Also, did you get Ann on your list when you ran the brute force searcher--it should've appeared quite quickly because "Ann" begins with an "A"?

EDIT: And thank you so much for doing all this

**Comment by towerofnix** [comment]
Uhh it just spits out a bunch of text right away, and eventually "Ann &lt;&lt;BOOM>> (32, 32)". I can't do anything with the input box because it starts spitting out text right away! :P

**Comment by joker314** [comment]
Yep, text box actually does nothing! 😛 

Okay, so my tool isn't going to be too browser cross-compatible. But!! If it _does_ spit out "Ann", then the tool has managed to crack the redaction stuffs so I think I need to swap out Chrome for Firefox. May I ask, what version of Firefox do you use?

**Comment by towerofnix** [comment]
Firefox 60.0b14 (64-bit) on a Debian linux.

**Comment by joker314** [comment]
Okay, thanks! Closing as resolved

**Comment by joker314** [comment]
Actually, one more thing, for words beginning with "D" in your results, could you estimate roughly how many there were? I, on Chrome, get 2 -- but given FF seems to round, I'd expect it to give out more. If this is the case, it might not be viable either :(

**Comment by joker314** [comment]
Actually, dw about it -- I'll install FF and find out
